name: PHPUnit (Unit Tests)

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: php-actions/composer@v6 # or alternative dependency management

      - name: Install QPDF & Run PHPUnit
        run: |
          sudo apt install -y qpdf
          vendor/bin/phpunit --color=always